cargo-features = ["codegen-backend"]

[package]
name = "gpui-test"
version = "0.1.0"
edition = "2024"

[dependencies.gpui]
git = "https://github.com/happenslol/zed"
branch = "dev"
default-features = false
features = ["wayland", "http_client"]

[profile.dev]
debug = 1
codegen-backend = "cranelift"
